// Label kategori, nama (bila perlu), dan tagline 65 demo dalam bahasa Inggris & Melayu.
// Situs demonya sendiri berbahasa Indonesia; teks di sini hanya untuk galeri.
import type { DemoCategory } from '../lib/demos'

type DemoText = { name?: string; tagline: string }

export const DEMO_CATEGORY_TEXT: Record<'en' | 'ms', Record<DemoCategory, string>> = {
  en: {
    landing: 'Landing Page',
    undangan: 'Digital Invitation',
    linkinbio: 'Link in Bio',
    portfolio: 'Portfolio',
    reservasi: 'Online Booking',
    properti: 'Property Marketplace',
    todo: 'Productivity App',
    kontes: 'Design Contest',
  },
  ms: {
    landing: 'Landing Page',
    undangan: 'Kad Jemputan Digital',
    linkinbio: 'Link in Bio',
    portfolio: 'Portfolio',
    reservasi: 'Tempahan Dalam Talian',
    properti: 'Pasaran Hartanah',
    todo: 'Aplikasi Produktiviti',
    kontes: 'Peraduan Reka Bentuk',
  },
}

export const DEMO_TEXT: Record<'en' | 'ms', Record<string, DemoText>> = {
  en: {
    bribu: { tagline: 'A design-brief board where three sketches get paid' },
    cissycoffee: { tagline: 'A coffee shop with a chalkboard menu' },
    citarasa: { tagline: 'An old family restaurant, now taking orders by phone' },
    eduplay: { tagline: 'Primary-school maths, ten minutes a day' },
    elevinar: { tagline: 'Presentations people actually listen to' },
    lumicast: { tagline: 'Training broadcasts for organisation leaders' },
    luxeelectro: { tagline: 'Audio gear with fully written specifications' },
    modewear: { tagline: 'Workwear tailored after you order' },
    nexttalks: { tagline: 'Four speakers, one table' },
    nimbus: { tagline: 'Servers in Indonesia, with a public status page' },
    rasanusantara: { tagline: 'Standardised recipe cards for restaurant kitchens' },
    sanzyhub: { tagline: 'A multi-page Next.js landing page template' },
    skywings: { tagline: 'An on-time intercity airline' },
    sribu: { tagline: 'An unofficial redesign concept' },
    tastycorner: { tagline: 'A weekly receipt for food businesses' },
    woodora: { tagline: 'Made-to-measure solid wood furniture' },
    zychrome: { tagline: 'A webinar that answers back' },
    corporate: { name: 'Corporate Event Website', tagline: 'Temu Rekayasa Nusa 2027' },
    aqiqah: { name: 'Digital Aqiqah Invitation', tagline: 'Aisyah Khairunnisa' },
    khitanan: { name: 'Digital Circumcision Celebration Invitation', tagline: 'Kapten Fauzan' },
    wedding: { name: 'Digital Wedding Invitation', tagline: 'Raka & Sinta' },
    reuni: { name: 'Digital Reunion Invitation', tagline: 'Class of 2010, SMA Kencana Mulia' },
    engagement: { name: 'Digital Engagement Invitation', tagline: 'Raka & Sinta' },
    birthday: { name: 'Digital Birthday Invitation', tagline: 'Kayla' },
    wisuda: { name: 'Digital Graduation Invitation', tagline: 'Dimas Prasetyo' },
    arsip: { tagline: 'Writer & poet, Yogyakarta' },
    atlas: { tagline: 'Brand & design consultancy, Bandung' },
    cipher: { tagline: 'Security researcher & CTF player' },
    disko: { tagline: 'A funk-disco band from Bandung' },
    jajan: { tagline: 'Traditional snacks & rice bowls, Bandung' },
    kaset: { tagline: 'Mixtapes & community radio, Bandung' },
    vendra: { tagline: 'A home-grown coffee shop in Bandung' },
    vinyl: { tagline: 'Singer & songwriter' },
    mellow: { tagline: 'Illustrator & sticker artist' },
    nova: { tagline: 'Creative technologist' },
    pulse: { tagline: 'Motion designer' },
    zen: { tagline: 'Mindfulness teacher & tea companion' },
    aria: { tagline: 'A glassmorphism portfolio for creative developers' },
    carlos: { tagline: 'A dark portfolio for designers & developers' },
    celeste: { tagline: 'An editorial portfolio for brand designers' },
    milo: { tagline: 'A bento-grid portfolio for illustrators' },
    noelle: { tagline: 'A minimal portfolio for UI/UX designers' },
    rex: { tagline: 'A neo-brutalist portfolio for graphic designers' },
    sorelle: { tagline: 'A cheerful portfolio for UI/UX designers' },
    futsal: { tagline: 'Futsal court booking' },
    klinik: { tagline: 'Doctor appointments' },
    restoran: { tagline: 'Book a table from the floor plan' },
    hotel: { tagline: 'Book a room at the end of the bay' },
    bioskop: { tagline: 'Buy tickets & choose your seat' },
    beranda: { tagline: 'Choose the neighbourhood first' },
    homigo: { tagline: 'First homes & rentals' },
    lumora: { tagline: 'Luxury homes, private viewings' },
    propertia: { tagline: 'Curated homes' },
    'classic-todo': { tagline: 'One list for one day' },
    'kanban-board': { tagline: 'A kanban board with WIP limits' },
    'task-manager': { tagline: 'A task manager with a calendar' },
    'absorber-dickson': { tagline: 'Corporate concept' },
    'absorber-divine': { tagline: 'Divine concept' },
    'absorber-premium': { tagline: 'Premium concept' },
    'absorber-segar': { tagline: 'Fresh concept' },
    'crave-amber': { tagline: 'Amber concept' },
    'crave-close': { tagline: 'Close concept' },
    'crave-grace': { tagline: 'Grace concept' },
    'crave-lumen': { tagline: 'Lumen concept' },
    'crave-noir': { tagline: 'Noir concept' },
  },
  ms: {
    bribu: { tagline: 'Papan taklimat reka bentuk, tiga lakaran dibayar' },
    cissycoffee: { tagline: 'Kedai kopi dengan menu papan kapur' },
    citarasa: { tagline: 'Restoran lama, kini terima pesanan dari telefon' },
    eduplay: { tagline: 'Matematik sekolah rendah, sepuluh minit sehari' },
    elevinar: { tagline: 'Pembentangan yang benar-benar didengar' },
    lumicast: { tagline: 'Siaran latihan untuk pengurus organisasi' },
    luxeelectro: { tagline: 'Peralatan audio dengan spesifikasi lengkap' },
    modewear: { tagline: 'Pakaian kerja dijahit selepas ditempah' },
    nexttalks: { tagline: 'Empat penceramah, satu meja' },
    nimbus: { tagline: 'Pelayan di Indonesia, status yang terbuka' },
    rasanusantara: { tagline: 'Kad resipi standard untuk dapur restoran' },
    sanzyhub: { tagline: 'Templat landing page Next.js berbilang halaman' },
    skywings: { tagline: 'Syarikat penerbangan antara bandar yang tepat masa' },
    sribu: { tagline: 'Konsep reka semula tidak rasmi' },
    tastycorner: { tagline: 'Resit mingguan untuk perniagaan makanan' },
    woodora: { tagline: 'Perabot kayu padu ikut ukuran' },
    zychrome: { tagline: 'Webinar yang boleh membalas anda' },
    corporate: { name: 'Laman Acara Korporat Digital', tagline: 'Temu Rekayasa Nusa 2027' },
    aqiqah: { name: 'Kad Jemputan Akikah Digital', tagline: 'Aisyah Khairunnisa' },
    khitanan: { name: 'Kad Jemputan Majlis Berkhatan Digital', tagline: 'Kapten Fauzan' },
    wedding: { name: 'Kad Jemputan Perkahwinan Digital', tagline: 'Raka & Sinta' },
    reuni: { name: 'Kad Jemputan Majlis Reunion Digital', tagline: 'Angkatan 2010 SMA Kencana Mulia' },
    engagement: { name: 'Kad Jemputan Pertunangan Digital', tagline: 'Raka & Sinta' },
    birthday: { name: 'Kad Jemputan Hari Jadi Digital', tagline: 'Kayla' },
    wisuda: { name: 'Kad Jemputan Konvokesyen Digital', tagline: 'Dimas Prasetyo' },
    arsip: { tagline: 'Penulis & penyair, Yogyakarta' },
    atlas: { tagline: 'Perunding jenama & reka bentuk, Bandung' },
    cipher: { tagline: 'Penyelidik keselamatan & pemain CTF' },
    disko: { tagline: 'Kumpulan funk-disko dari Bandung' },
    jajan: { tagline: 'Kuih tradisional & nasi mangkuk, Bandung' },
    kaset: { tagline: 'Mixtape & radio komuniti, Bandung' },
    vendra: { tagline: 'Kedai kopi rumahan di Bandung' },
    vinyl: { tagline: 'Penyanyi & penulis lagu' },
    mellow: { tagline: 'Ilustrator & artis pelekat' },
    nova: { tagline: 'Teknologis kreatif' },
    pulse: { tagline: 'Pereka grafik gerak' },
    zen: { tagline: 'Guru kesedaran minda & teman minum teh' },
    aria: { tagline: 'Portfolio kaca untuk pembangun kreatif' },
    carlos: { tagline: 'Portfolio gelap untuk pereka & pembangun' },
    celeste: { tagline: 'Portfolio editorial untuk pereka jenama' },
    milo: { tagline: 'Portfolio bento untuk ilustrator' },
    noelle: { tagline: 'Portfolio minimalis untuk pereka UI/UX' },
    rex: { tagline: 'Portfolio neo-brutalis untuk pereka grafik' },
    sorelle: { tagline: 'Portfolio ceria untuk pereka UI/UX' },
    futsal: { tagline: 'Tempahan gelanggang futsal' },
    klinik: { tagline: 'Temu janji doktor' },
    restoran: { tagline: 'Tempah meja melalui pelan lantai' },
    hotel: { tagline: 'Tempah bilik di hujung teluk' },
    bioskop: { tagline: 'Beli tiket & pilih tempat duduk' },
    beranda: { tagline: 'Pilih kawasannya dahulu' },
    homigo: { tagline: 'Rumah pertama & tempat sewa' },
    lumora: { tagline: 'Kediaman mewah, lawatan peribadi' },
    propertia: { tagline: 'Rumah yang dikurasi' },
    'classic-todo': { tagline: 'Satu senarai untuk satu hari' },
    'kanban-board': { tagline: 'Papan kanban dengan had WIP' },
    'task-manager': { tagline: 'Pengurus tugasan dengan kalendar' },
    'absorber-dickson': { tagline: 'Konsep korporat' },
    'absorber-divine': { tagline: 'Konsep Divine' },
    'absorber-premium': { tagline: 'Konsep premium' },
    'absorber-segar': { tagline: 'Konsep segar' },
    'crave-amber': { tagline: 'Konsep Amber' },
    'crave-close': { tagline: 'Konsep Close' },
    'crave-grace': { tagline: 'Konsep Grace' },
    'crave-lumen': { tagline: 'Konsep Lumen' },
    'crave-noir': { tagline: 'Konsep Noir' },
  },
}
