// Teks paket dalam bahasa Inggris & Melayu. Harga dan slug TIDAK ada di sini —
// keduanya selalu dari lib/packages.ts.
import type { Paket } from '../lib/packages'

type PaketText = Pick<Paket, 'title' | 'subtitle' | 'duration' | 'highlights' | 'features'> & { badge?: string }

export const PACKAGE_TEXT: Record<'en' | 'ms', Record<string, PaketText>> = {
  en: {
    'landing-page': {
      title: 'Landing Page',
      badge: 'Starter',
      subtitle: 'One promotional page built to convert',
      duration: '1–3 working days',
      highlights: ['Product launches', 'Events', 'Ad campaigns'],
      features: [
        'One promotional page focused on conversion',
        'Modern, mobile-friendly design',
        'Free .com/.xyz domain + SSL for 1 year',
        'Speed optimisation & basic SEO',
        'Contact form + WhatsApp button',
        'Bonus: CDN & 1 month of maintenance',
      ],
    },
    'standar-umkm': {
      title: 'Small Business Standard',
      badge: 'Business',
      subtitle: 'The most popular choice for businesses',
      duration: '3–5 working days',
      highlights: ['Company profile', 'Services', 'Small businesses'],
      features: [
        '3–5 complete pages (Home, About, Services, Blog, Contact)',
        'Professional, responsive design',
        '.com domain + hosting + SSL',
        'Contact form, WhatsApp & Google Maps',
        'Basic copywriting & on-page SEO setup',
        '2 rounds of design revisions',
        'Maintenance & security support for 1–3 months',
      ],
    },
    'toko-online-simple': {
      title: 'Simple Online Store',
      badge: 'Premium',
      subtitle: 'Start selling online without the hassle',
      duration: '1–2 weeks',
      highlights: ['Product catalogue', 'Orders via WhatsApp', 'Retail shops'],
      features: [
        'Product catalogue of up to 20 items',
        'Checkout via WhatsApp (direct orders)',
        'Product categories & promo banners',
        'Responsive design + fast performance',
        'Lightweight CMS – easy product updates',
        '2 rounds of layout/content revisions',
        'Domain + hosting + SSL included',
      ],
    },
    'website-custom': {
      title: 'Custom Website',
      badge: 'Custom',
      subtitle: 'Design and features built entirely around your needs',
      duration: '1–2 weeks, depending on features',
      highlights: ['Start-ups', 'Institutions', 'Bespoke systems'],
      features: [
        'Fully custom design & layout',
        'Flexible number of pages & features',
        'API integrations, booking, complex forms',
        'Modern framework (Next.js, Tailwind, etc.)',
        'UX consultation & performance tuning',
        '3 months of maintenance & technical support',
        'Suited to start-ups & institutions',
      ],
    },
    'toko-online-full': {
      title: 'Full Online Store',
      subtitle: 'A complete online store with an admin dashboard',
      duration: '1–2 weeks, depending on features',
      highlights: ['E-commerce', 'Automatic shipping rates', 'Order management'],
      features: [
        'Shopping cart & full checkout',
        'Payment gateway integration',
        'Automatic shipping rates (via RajaOngkir)',
        'Admin dashboard – manage products & orders',
        'Mobile-first design, fast loading & SEO-ready',
        '3–6 months of maintenance & support',
        'Domain + hosting + premium SSL',
      ],
    },
    portofolio: {
      title: 'Portfolio / Personal Branding',
      subtitle: 'A showcase of work for freelancers & creators',
      duration: '3–5 working days',
      highlights: ['Freelancers', 'Creators', 'Professionals'],
      features: [
        'About, Work, Blog & Contact pages',
        'Clean, professional design',
        'Calls to action to WhatsApp, LinkedIn, Instagram, etc.',
        'Basic SEO & a tidy heading structure',
        'Domain + hosting + SSL for 1 year',
        'Ideal for freelancers & creators',
      ],
    },
  },
  ms: {
    'landing-page': {
      title: 'Landing Page',
      badge: 'Permulaan',
      subtitle: 'Satu halaman promosi yang fokus pada penukaran',
      duration: '1–3 hari bekerja',
      highlights: ['Promosi produk', 'Acara', 'Kempen iklan'],
      features: [
        '1 halaman promosi yang fokus pada penukaran',
        'Reka bentuk moden & mesra mudah alih',
        'Domain .com/.xyz percuma + SSL 1 tahun',
        'Pengoptimuman kelajuan & SEO asas',
        'Borang hubungan + butang WhatsApp',
        'Bonus: CDN & penyelenggaraan 1 bulan',
      ],
    },
    'standar-umkm': {
      title: 'Standard PKS',
      badge: 'Perniagaan',
      subtitle: 'Pilihan paling popular untuk perniagaan',
      duration: '3–5 hari bekerja',
      highlights: ['Profil syarikat', 'Perkhidmatan', 'PKS'],
      features: [
        '3–5 halaman lengkap (Utama, Profil, Perkhidmatan, Blog, Hubungi)',
        'Reka bentuk profesional & responsif',
        'Domain .com + hosting + SSL',
        'Borang hubungan, WhatsApp & Google Maps',
        'Penulisan asas & persediaan SEO on-page',
        '2× semakan reka bentuk',
        'Sokongan penyelenggaraan & keselamatan 1–3 bulan',
      ],
    },
    'toko-online-simple': {
      title: 'Kedai Online Ringkas',
      badge: 'Premium',
      subtitle: 'Mula berniaga dalam talian tanpa kerumitan',
      duration: '1–2 minggu',
      highlights: ['Katalog produk', 'Pesanan melalui WhatsApp', 'Kedai runcit'],
      features: [
        'Katalog produk sehingga 20 item',
        'Pembayaran melalui WhatsApp (pesanan terus)',
        'Kategori produk & sepanduk promosi',
        'Reka bentuk responsif + prestasi pantas',
        'CMS ringan – mudah kemas kini produk',
        '2× semakan paparan/kandungan',
        'Domain + hosting + SSL sudah termasuk',
      ],
    },
    'website-custom': {
      title: 'Laman Web Tersuai',
      badge: 'Tersuai',
      subtitle: 'Reka bentuk & ciri sepenuhnya mengikut keperluan',
      duration: '1–2 minggu, bergantung pada ciri',
      highlights: ['Syarikat pemula', 'Institusi', 'Sistem khas'],
      features: [
        'Reka bentuk & susun atur tersuai sepenuhnya',
        'Bilangan halaman & ciri yang fleksibel',
        'Integrasi API, tempahan, borang kompleks',
        'Rangka kerja moden (Next.js, Tailwind, dsb.)',
        'Konsultasi UX & pengoptimuman prestasi',
        'Penyelenggaraan & sokongan teknikal 3 bulan',
        'Sesuai untuk syarikat pemula & institusi',
      ],
    },
    'toko-online-full': {
      title: 'Kedai Online Penuh',
      subtitle: 'Kedai dalam talian lengkap dengan papan pemuka admin',
      duration: '1–2 minggu, bergantung pada ciri',
      highlights: ['E-dagang', 'Kos penghantaran automatik', 'Urus pesanan'],
      features: [
        'Troli beli-belah & proses pembayaran lengkap',
        'Integrasi gerbang pembayaran',
        'Kos penghantaran automatik (melalui RajaOngkir)',
        'Papan pemuka admin – urus produk & pesanan',
        'Reka bentuk mudah alih dahulu, pantas & sedia SEO',
        'Penyelenggaraan & sokongan 3–6 bulan',
        'Domain + hosting + SSL premium',
      ],
    },
    portofolio: {
      title: 'Portfolio / Penjenamaan Peribadi',
      subtitle: 'Pameran karya untuk pekerja bebas & pencipta kandungan',
      duration: '3–5 hari bekerja',
      highlights: ['Pekerja bebas', 'Pencipta kandungan', 'Profesional'],
      features: [
        'Halaman Tentang, Karya, Blog & Hubungi',
        'Reka bentuk kemas & profesional',
        'Butang ke WhatsApp, LinkedIn, Instagram, dsb.',
        'SEO asas & struktur tajuk yang kemas',
        'Domain + hosting + SSL 1 tahun',
        'Sesuai untuk pekerja bebas & pencipta kandungan',
      ],
    },
  },
}
